name: CI

on:
  push:

jobs:
  test:
    name: "🧪 Test"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: "⚙️ Install Ruby and dependencies"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "🎨 Lint"
        run: bundle exec rubocop

      - name: "🧪 Test"
        run: bundle exec rake test

      - name: "📊 Coverage"
        run: bundle exec rake check_coverage
